CREATE DATABASE REIDOACAI;
USE REIDOACAI;

CREATE TABLE ENDERECO(
ID_END INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
RUA VARCHAR(100),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO CHAR(2),
CEP CHAR(8),
NUMERO VARCHAR(4),
COMPLEMENTO VARCHAR(50)
);

CREATE TABLE CLIENTE(
ID_CLI INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_CLI VARCHAR(30),
CPF_CLI CHAR(14),
TEL_CLI CHAR(14),
USUARIO VARCHAR(30),
SENHA VARCHAR(30),
COD_END INT NOT NULL REFERENCES ENDERECO(ID_END)
);

CREATE TABLE PRODUTO(
ID_PROD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_PROD VARCHAR(30),
TIPO_PROD VARCHAR(30),
VALOR_PROD DECIMAL(5,2),
ESTOQUE INTEGER,
IMAGEM VARCHAR(255)
);

CREATE TABLE ADICIONAL(
ID_ADC INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_ADC VARCHAR(30),
VALOR_ADC DECIMAL(5,2),
ESTOQUE INTEGER,
IMAGEM VARCHAR(255)
);

CREATE TABLE ITEM_PEDIDO(
ID_ITEM_PED INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
QUANTIDADE INTEGER ,
SUBTOTAL DECIMAL(5,2),
COD_ADC INT NOT NULL REFERENCES ADICIONAL(ID_ADC),
COD_PROD INT NOT NULL REFERENCES PRODUTO(ID_PROD)
);

CREATE TABLE PEDIDO(
ID_PED INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
STATUS_PED VARCHAR(20),
METODO_PAG VARCHAR(30),
VALOR_TOTAL DECIMAL(5,2),
DATA_PED DATETIME,
COD_ITEM_PED INT NOT NULL REFERENCES ITEM_PEDIDO(ID_ITEM_PED),
COD_END INT NOT NULL REFERENCES endereco(ID_END),
COD_CLI INT NOT NULL REFERENCES CLIENTE(ID_CLI)
);

INSERT INTO ENDERECO(RUA,BAIRRO,CIDADE,ESTADO,CEP,NUMERO,COMPLEMENTO)
VALUES('Rua 13 de Maio','Centro','Paulo de Faria','SP','15490015','498','Casa de esquina');

INSERT INTO produto(NOME_PROD,TIPO_PROD,VALOR_PROD,ESTOQUE,IMAGEM)
VALUES('Açaí 400ml','Copo',25.00,20,'imagem/400ml.jpeg');
VALUES('Açaí 500ml', 'Copo', 27.00,'imagem/500ml.jpeg');
VALUES('Açaí 700ml', 'Copo', 35.00,'imagem/700ml.png');
VALUES('Açaí 1litro', 'Pote', 50.00,'imagem/1litro.jpeg');

INSERT INTO ADICIONAL(NOME_ADC,VALOR_ADC,ESTOQUE,IMAGEM)
VALUES('Creme de avelã',0.0,50,'imagem/avela');
VALUES ('Creme de Ovo Maltine',0,50,'imagem/ovomaltine');
VALUES('Creme de Kinder Bueno',0,50,'imagem/kinderbueno');
VALUES('Creme de Rafaello',0,50,'imagem/rafaello');
VALUES('Creme de Oreo',0,50,'imagem/oreo');
VALUES('Creme de morango',0,50,'imagem/crememorango');
VALUES('Creme de ninho(chantilly)',0,50,'imagem/cremeninho');
VALUES('Recheio de ninho(tipo chocolate branco',0,50,'imagem/recheioninho');
VALUES('Gotas de chocolate',0,50,'imagem/gotaschocolate');
VALUES('Disquete',0,50,'imagem/disquete');
VALUES('Kit Kat',0,50,'imagem/kitkat');
