CREATE DATABASE REIDOACAI;
USE REIDOACAI;

CREATE TABLE ENDERECO(
ID_END INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
RUA VARCHAR(100),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO CHAR(2),
CEP CHAR(8),
NUMERO VARCHAR(4),
COMPLEMENTO VARCHAR(50)
);

CREATE TABLE CLIENTE(
ID_CLI INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_CLI VARCHAR(30),
CPF_CLI CHAR(14),
TEL_CLI CHAR(14),
USUARIO VARCHAR(30),
SENHA VARCHAR(30),
COD_END INT NOT NULL REFERENCES ENDERECO(ID_END)
);

CREATE TABLE PRODUTO(
ID_PROD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_PROD VARCHAR(30),
TIPO_PROD VARCHAR(30),
VALOR_PROD DECIMAL(5,2),
ESTOQUE INTEGER
);

CREATE TABLE ADICIONAL(
ID_ADC INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_ADC VARCHAR(30),
VALOR_ADC DECIMAL(5,2),
ESTOQUE INTEGER
);

CREATE TABLE ITEM_PEDIDO(
ID_ITEM_PED INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
QUANTIDADE INTEGER ,
SUBTOTAL DECIMAL(5,2),
COD_ADC INT NOT NULL REFERENCES ADICIONAL(ID_ADC),
COD_PROD INT NOT NULL REFERENCES PRODUTO(ID_PROD)
);

CREATE TABLE PEDIDO(
ID_PED INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
STATUS_PED VARCHAR(20),
METODO_PAG VARCHAR(30),
VALOR_TOTAL DECIMAL(5,2),
DATA_PED DATETIME,
COD_ITEM_PED INT NOT NULL REFERENCES ITEM_PEDIDO(ID_ITEM_PED),
COD_END INT NOT NULL REFERENCES endereco(ID_END),
COD_CLI INT NOT NULL REFERENCES CLIENTE(ID_CLI)
);

INSERT INTO ENDERECO(RUA,BAIRRO,CIDADE,ESTADO,CEP,NUMERO,COMPLEMENTO)
VALUES('Rua 13 de Maio','Centro','Paulo de Faria','SP','15490015','498','Casa de esquina');

INSERT INTO TABLE cliente (NOME_CLI,CPF_CLI,TEL_CLI,USUARIO,SENHA,CODEND)
VALUES/**/